# First Github Actions workflow

name: Build Application

runs:
  using: composite

  steps:
  - name: Checkout repository
    # run: git clone https://github.com/ashegde/course-app.git .
    uses: actions/checkout@v4

  - name: Install Python 3.11
    uses: actions/setup-python@v5
    with:
      python-version: '3.11' 

  - name: Install Poetry
    uses: snok/install-poetry@v1
    # run: |
    #   curl -sSL https://install.python-poetry.org | python3 - 
    #   export PATH=$HOME/.local/bin:$PATH
    with:
      virtualenvs-in-project: true

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os}}-${{ hashFiles('**/poetry.lock') }}

  - name: Install app dependencies with poetry
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    # run: poetry install
    run: poetry run make install
    shell: bash


      


